### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by michaelspeed** [wantpinow/nuxt-editorjs#1]
Does not work with nuxt 3,
Throws -

```ReferenceError: window is not defined
    at Object.<anonymous> (/Volumes/HAMILTON/projects/gidus/gidus-admin/node_modules/@editorjs/editorjs/dist/editor.js:2:198)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file:///Volumes/HAMILTON/projects/gidus/gidus-admin/.nuxt/dist/server/server.mjs:81339:3)```

**Comment by wantpinow** [comment]
Hi @michaelspeed can you provide a reproducible example for this error? Before that, there have been a few minor updates which may have fixed your issue so it's worth upgrading to the latest version.
